// Google Translate supported language codes — all verified
export const LANGUAGES = [
  // Auto detect
  { code: 'auto', name: 'Auto Detect', flag: '🌐' },

  // Indian Languages (Google-verified codes)
  { code: 'hi',  name: 'Hindi',           flag: '🇮🇳' },
  { code: 'bn',  name: 'Bengali',         flag: '🇮🇳' },
  { code: 'te',  name: 'Telugu',          flag: '🇮🇳' },
  { code: 'mr',  name: 'Marathi',         flag: '🇮🇳' },
  { code: 'ta',  name: 'Tamil',           flag: '🇮🇳' },
  { code: 'gu',  name: 'Gujarati',        flag: '🇮🇳' },
  { code: 'kn',  name: 'Kannada',         flag: '🇮🇳' },
  { code: 'ml',  name: 'Malayalam',       flag: '🇮🇳' },
  { code: 'pa',  name: 'Punjabi',         flag: '🇮🇳' },
  { code: 'or',  name: 'Odia',            flag: '🇮🇳' },
  { code: 'as',  name: 'Assamese',        flag: '🇮🇳' },
  { code: 'ur',  name: 'Urdu',            flag: '🇮🇳' },
  { code: 'sa',  name: 'Sanskrit',        flag: '🇮🇳' },
  { code: 'ne',  name: 'Nepali',          flag: '🇳🇵' },
  { code: 'si',  name: 'Sinhala',         flag: '🇱🇰' },
  { code: 'sd',  name: 'Sindhi',          flag: '🇮🇳' },
  { code: 'ks',  name: 'Kashmiri',        flag: '🇮🇳' },
  { code: 'bho', name: 'Bhojpuri',        flag: '🇮🇳' },
  { code: 'mai', name: 'Maithili',        flag: '🇮🇳' },
  { code: 'doi', name: 'Dogri',           flag: '🇮🇳' },
  { code: 'mni-Mtei', name: 'Manipuri',   flag: '🇮🇳' },
  { code: 'sat', name: 'Santali',         flag: '🇮🇳' },
  { code: 'gom', name: 'Konkani',         flag: '🇮🇳' },
  { code: 'lus', name: 'Mizo',            flag: '🇮🇳' },

  // Global Languages
  { code: 'en',    name: 'English',              flag: '🇬🇧' },
  { code: 'es',    name: 'Spanish',              flag: '🇪🇸' },
  { code: 'fr',    name: 'French',               flag: '🇫🇷' },
  { code: 'de',    name: 'German',               flag: '🇩🇪' },
  { code: 'it',    name: 'Italian',              flag: '🇮🇹' },
  { code: 'pt',    name: 'Portuguese',           flag: '🇵🇹' },
  { code: 'ru',    name: 'Russian',              flag: '🇷🇺' },
  { code: 'zh-CN', name: 'Chinese (Simplified)', flag: '🇨🇳' },
  { code: 'zh-TW', name: 'Chinese (Traditional)',flag: '🇹🇼' },
  { code: 'ja',    name: 'Japanese',             flag: '🇯🇵' },
  { code: 'ko',    name: 'Korean',               flag: '🇰🇷' },
  { code: 'ar',    name: 'Arabic',               flag: '🇸🇦' },
  { code: 'tr',    name: 'Turkish',              flag: '🇹🇷' },
  { code: 'vi',    name: 'Vietnamese',           flag: '🇻🇳' },
  { code: 'th',    name: 'Thai',                 flag: '🇹🇭' },
  { code: 'id',    name: 'Indonesian',           flag: '🇮🇩' },
  { code: 'ms',    name: 'Malay',                flag: '🇲🇾' },
  { code: 'nl',    name: 'Dutch',                flag: '🇳🇱' },
  { code: 'pl',    name: 'Polish',               flag: '🇵🇱' },
  { code: 'sv',    name: 'Swedish',              flag: '🇸🇪' },
  { code: 'da',    name: 'Danish',               flag: '🇩🇰' },
  { code: 'fi',    name: 'Finnish',              flag: '🇫🇮' },
  { code: 'no',    name: 'Norwegian',            flag: '🇳🇴' },
  { code: 'cs',    name: 'Czech',                flag: '🇨🇿' },
  { code: 'sk',    name: 'Slovak',               flag: '🇸🇰' },
  { code: 'hu',    name: 'Hungarian',            flag: '🇭🇺' },
  { code: 'ro',    name: 'Romanian',             flag: '🇷🇴' },
  { code: 'bg',    name: 'Bulgarian',            flag: '🇧🇬' },
  { code: 'hr',    name: 'Croatian',             flag: '🇭🇷' },
  { code: 'uk',    name: 'Ukrainian',            flag: '🇺🇦' },
  { code: 'el',    name: 'Greek',                flag: '🇬🇷' },
  { code: 'he',    name: 'Hebrew',               flag: '🇮🇱' },
  { code: 'fa',    name: 'Persian',              flag: '🇮🇷' },
  { code: 'sw',    name: 'Swahili',              flag: '🇰🇪' },
  { code: 'af',    name: 'Afrikaans',            flag: '🇿🇦' },
  { code: 'sq',    name: 'Albanian',             flag: '🇦🇱' },
  { code: 'hy',    name: 'Armenian',             flag: '🇦🇲' },
  { code: 'az',    name: 'Azerbaijani',          flag: '🇦🇿' },
  { code: 'eu',    name: 'Basque',               flag: '🏴' },
  { code: 'be',    name: 'Belarusian',           flag: '🇧🇾' },
  { code: 'ca',    name: 'Catalan',              flag: '🏴' },
  { code: 'et',    name: 'Estonian',             flag: '🇪🇪' },
  { code: 'gl',    name: 'Galician',             flag: '🏴' },
  { code: 'ka',    name: 'Georgian',             flag: '🇬🇪' },
  { code: 'is',    name: 'Icelandic',            flag: '🇮🇸' },
  { code: 'lv',    name: 'Latvian',              flag: '🇱🇻' },
  { code: 'lt',    name: 'Lithuanian',           flag: '🇱🇹' },
  { code: 'mk',    name: 'Macedonian',           flag: '🇲🇰' },
  { code: 'mt',    name: 'Maltese',              flag: '🇲🇹' },
  { code: 'sr',    name: 'Serbian',              flag: '🇷🇸' },
  { code: 'sl',    name: 'Slovenian',            flag: '🇸🇮' },
  { code: 'tl',    name: 'Filipino',             flag: '🇵🇭' },
  { code: 'km',    name: 'Khmer',                flag: '🇰🇭' },
  { code: 'lo',    name: 'Lao',                  flag: '🇱🇦' },
  { code: 'my',    name: 'Myanmar (Burmese)',     flag: '🇲🇲' },
  { code: 'mn',    name: 'Mongolian',            flag: '🇲🇳' },
  { code: 'am',    name: 'Amharic',              flag: '🇪🇹' },
  { code: 'so',    name: 'Somali',               flag: '🇸🇴' },
  { code: 'zu',    name: 'Zulu',                 flag: '🇿🇦' },
  { code: 'xh',    name: 'Xhosa',               flag: '🇿🇦' },
  { code: 'yo',    name: 'Yoruba',               flag: '🇳🇬' },
  { code: 'ig',    name: 'Igbo',                 flag: '🇳🇬' },
  { code: 'ha',    name: 'Hausa',                flag: '🇳🇬' },
  { code: 'cy',    name: 'Welsh',                flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿' },
  { code: 'jw',    name: 'Javanese',             flag: '🇮🇩' },
  { code: 'ceb',   name: 'Cebuano',              flag: '🇵🇭' },
  { code: 'hmn',   name: 'Hmong',                flag: '🌏' },
  { code: 'la',    name: 'Latin',                flag: '🏛️' },
  { code: 'eo',    name: 'Esperanto',            flag: '🌍' },
];

export const getLanguageName = (code) => {
  const lang = LANGUAGES.find(l => l.code === code);
  return lang ? lang.name : code;
};

export const getLanguageFlag = (code) => {
  const lang = LANGUAGES.find(l => l.code === code);
  return lang ? lang.flag : '🌐';
};
